AllCops:
  TargetRubyVersion: 3.2 # Make sure this matches your installed Ruby version

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/LineLength:
  Max: 100 # Set max line length to 100 characters

Metrics/BlockLength:
  Max: 100 # or any number you feel is reasonable
